#!/bin/bash -e                                                                                                                                                                                                                     
                                                                                                                                                                                                                                   
# Check whether C++ sources formatting is compliant to clang-format.
for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$'`; do                                                                                                                                          
    if [ -f "${file}" ]; then                                                                                                                                                                                                      
        clang-format --style=file --dry-run --Werror "${file}"                                                                                                                                                                     
    fi                                                                                                                                                                                                                             
done
